#!/bin/bash

S3_PATH="s3://dgamliel-minecraft-jars/worlds/dgamliel/mc_world.zip"
LOCAL_PATH="/world"

if [ -f "$HOME/.aws/credentials" ]; then
	echo "Found .aws/credentials file"
else
	echo "Unable to find .aws/credentials file"
	exit 1
fi


if aws s3 ls "$S3_PATH" >/dev/null 2>&1; then
	aws s3 cp "$S3_PATH" "$LOCAL_PATH"
fi

