#!/bin/bash
USER=$1
WORLD_NAME=$2

S3_PATH="s3://dgamliel-minecraft-jars/worlds/${USER}/${WORLD_NAME}/mc_world.zip"
LOCAL_PATH="/world"

if [ -f "$HOME/.aws/credentials" ]; then
	echo "Found .aws/credentials file"
else
	echo "Unable to find .aws/credentials file"
fi

if aws s3 ls "$S3_PATH" >/dev/null 2>&1; then
	aws s3 cp "$S3_PATH" "$LOCAL_PATH"
else
	echo "Unable to find world in $S3_PATH"
fi

