version: "3.8"

services:
  mc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mc
    environment:
      EULA: "true"
      WORLD: "/world"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - world:/world
    stdin_open: true
    tty: true
    restart: "no"

volumes:
  data: {}
  world: {}  
